theme: jekyll-theme-cayman
title: Start an application on the Data Science Research Infrastructure 📊
description: ⚡ A short workshop to start Data Science applications on the DSRI at Maastricht University
show_downloads: false