theme: jekyll-theme-cayman
title: Start Data Science applications on the DSRI 📊
description: ⚡ A short workshop to start Data Science applications on the Data Science Research Infrastructure at Maastricht University
show_downloads: false