theme: jekyll-theme-cayman
title: Start an application on the DSRI at UM 📊
description: ⚡ A short workshop to start Data Science applications on the Data Science Research Infrastructure at Maastricht University
show_downloads: false